version: "2"

services:
  web:
    ports:
      - "80:5000"
    build: ./server
    container_name: srcful-gw
    restart: always
    devices:
      - /dev/i2c-1
    labels:
      io.balena.features.dbus: 1
    volumes:
      - srcful-data:/data/srcful

  bluetooth:
    build: ./bluetooth
    container_name: ble
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.sysfs: 1
    depends_on:
      - "web"
      
volumes:
  srcful-data: