version: "2.4"

x-environment:
  &shared_env
  - REST_SERVICE_PORT: 80 # should correspond to the port in the web service below
  - REST_SERVICE_PORT_INTERNAL: 5000 # should correspond to the port in the web service below

services:

  web:
    ports:
      - 80:5000
    build: ./server
    container_name: srcful-gw
    restart: always
    environment:
      <<: *shared_env
    devices:
      - /dev/i2c-1
    labels:
      io.balena.features.dbus: 1
      io.balena.features.supervisor-api: 1
    volumes:
      - srcful-data:/data/srcful

  bluetooth:
    env_file:
      - ./compose.env
    build: ./bluetooth
    container_name: ble
    privileged: true
    network_mode: host
    environment:
      <<: *shared_env
    restart: always
    labels:
      io.balena.features.dbus: 1
      io.balena.features.kernel-modules: 1
      io.balena.features.sysfs: 1
    depends_on:
      - "web"
      
volumes:
  srcful-data: