version: "2"
services:
  web:
    ports:
      - "80:5000"
    build: ./server
    container_name: srcfull-gw
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1
  inverter:
    build: ./modbus_slave
    container_name: srcfull-inverter
    restart: always

