version: "2"
services:
  
  web:
    ports:
      - "80:5000"
    build: ./server
    container_name: srcfull-gw
    restart: always
    devices:
      - /dev/i2c-1:/dev/i2c-1
    labels:
      io.balena.features.dbus: 1
  
  inverter:
    build: ./modbus_slave
    container_name: srcfull-inverter
    restart: always

  bluetooth:
    build: ./bluetooth
    container_name: ble
    privileged: true
    network_mode: host
    restart: always
    labels:
      io.balena.features.dbus: 1

    depends_on:
      - "web"