version: "2"
services:
  web_nc:
    ports:
      - "8080:5000"
    build:
      context: ./server
      dockerfile: Dockerfile-no_crypt
    container_name: srcfull-gw
    restart: always
    privileged: true
    network_mode: host
    #devices:
    #  - /dev/ttyACM0:/dev/ttyACM0 # bluethooth
  inverter:
    build: ./modbus_slave
    container_name: srcfull-inverter
    restart: always
