version: "2"
services:
  web:
    ports:
      - "80:5000"
    build:
      context: ./server
      dockerfile: Dockerfile-no_crypt
    container_name: srcfull-gw
    restart: always
  inverter:
    build: ./modbus_slave
    container_name: srcfull-inverter
    restart: always
